name: Build and Deploy Docker Image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nodejs-app:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-nodejs-app:latest

      - name: Run the Container
        run: docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-nodejs-app:latest
